### ISSUE TITLE
Doesn't work with custom interface scaling

### ISSUE THREAD

**Issue by Atvaark** [Schwaxx/WFInfo#1]
Nothing gets detected if you use a custom UI scaling below 100. The rectangles that get scanned are way off so no text gets detected.

e. g. a custom scale of 70 means the UI is 30% smalled than expected.
A quick fix/hack that works reasonably is zooming the captured image by a factor of 100/scale before detecting text.

```
' Scale
Dim scaleIngame as Decimal = 70
Dim scale as Decimal = 100/scaleIngame
Dim scaledImage = New Bitmap(
    CliptoImage,
    CliptoImage.Width*scale,
    CliptoImage.Height*scale)
' Crop
Dim scaleGraphics = Graphics.FromImage(CliptoImage)
scaleGraphics.DrawImage(
    scaledImage,
    New Rectangle(
        0,
        0,
        CliptoImage.Width,
        CliptoImage.Height),
    New Rectangle(
        (scaledImage.Width - CliptoImage.Width)/2,
        (scaledImage.Height - CliptoImage.Height)/2,
        CliptoImage.Width,
        CliptoImage.Height),
    GraphicsUnit.Pixel)
scaleGraphics.Dispose()
```

The proper fix woud be to fix the `Public Function Crop` method to support scaling.
`Public Function Crop` also crashes by the way if for some reason a width/height of 0 is calculated.

The scale should be configurable of at least be read from the WF config files.
e. g. via
```
cat %localappdata%\Warframe\EE.cfg | grep Flash.FlashDrawScale=
Flash.FlashDrawScale=0.69663656
```

**Comment by TerohsLab** [comment]
It doesn't work with HUD scales higher then 100 either. Running Hud Scale 140 and OCR never gives me correctresults.
