### ISSUE TITLE
Some general ideas

### ISSUE THREAD

**Issue by TerohsLab** [Schwaxx/WFInfo#2]
* WFInfo should show the prices directly under the fissure rewards and not combined in a corner
* WFInfo should be able to get minimized and "closed" to the system tray
* Depending on what programming language / ui framework you use : Its not 1998 anymore. Custom fake XP skins are not cool anymore. Please let the OS decide how to theme your windows.

**Comment by Schwaxx** [comment]
1.) Let me know what you think of the new style results.

2.) This still isn't implemented, I'll consider it in the future.

3.) This was done purely because I like the retro style, so "deal with it" ;) (Appreciate the feedback though)
